version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: canteen_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: